# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gojuuon.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1024, 1440)
        Form.setMinimumSize(QtCore.QSize(1024, 1440))
        Form.setMaximumSize(QtCore.QSize(1024, 1440))
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 430, 971, 981))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.gridLayoutWidget.setFont(font)
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.a_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.a_button.setFont(font)
        self.a_button.setObjectName("a_button")
        self.gridLayout.addWidget(self.a_button, 0, 0, 1, 1)
        self.i_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.i_button.setFont(font)
        self.i_button.setObjectName("i_button")
        self.gridLayout.addWidget(self.i_button, 0, 1, 1, 1)
        self.uButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.uButton.setFont(font)
        self.uButton.setObjectName("uButton")
        self.gridLayout.addWidget(self.uButton, 0, 2, 1, 1)
        self.e_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.e_button.setFont(font)
        self.e_button.setObjectName("e_button")
        self.gridLayout.addWidget(self.e_button, 0, 3, 1, 1)
        self.o_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.o_button.setFont(font)
        self.o_button.setObjectName("o_button")
        self.gridLayout.addWidget(self.o_button, 0, 4, 1, 1)
        self.ki_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ki_button.setFont(font)
        self.ki_button.setObjectName("ki_button")
        self.gridLayout.addWidget(self.ki_button, 1, 1, 1, 1)
        self.shi_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.shi_button.setFont(font)
        self.shi_button.setObjectName("shi_button")
        self.gridLayout.addWidget(self.shi_button, 2, 1, 1, 1)
        self.chi_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.chi_button.setFont(font)
        self.chi_button.setObjectName("chi_button")
        self.gridLayout.addWidget(self.chi_button, 3, 1, 1, 1)
        self.ni_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ni_button.setFont(font)
        self.ni_button.setObjectName("ni_button")
        self.gridLayout.addWidget(self.ni_button, 4, 1, 1, 1)
        self.hi_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.hi_button.setFont(font)
        self.hi_button.setObjectName("hi_button")
        self.gridLayout.addWidget(self.hi_button, 5, 1, 1, 1)
        self.mi_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.mi_button.setFont(font)
        self.mi_button.setObjectName("mi_button")
        self.gridLayout.addWidget(self.mi_button, 6, 1, 1, 1)
        self.ri_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ri_button.setFont(font)
        self.ri_button.setObjectName("ri_button")
        self.gridLayout.addWidget(self.ri_button, 8, 1, 1, 1)
        self.ku_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ku_button.setFont(font)
        self.ku_button.setObjectName("ku_button")
        self.gridLayout.addWidget(self.ku_button, 1, 2, 1, 1)
        self.su_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.su_button.setFont(font)
        self.su_button.setObjectName("su_button")
        self.gridLayout.addWidget(self.su_button, 2, 2, 1, 1)
        self.tsu_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.tsu_button.setFont(font)
        self.tsu_button.setObjectName("tsu_button")
        self.gridLayout.addWidget(self.tsu_button, 3, 2, 1, 1)
        self.nu_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.nu_button.setFont(font)
        self.nu_button.setObjectName("nu_button")
        self.gridLayout.addWidget(self.nu_button, 4, 2, 1, 1)
        self.fu_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.fu_button.setFont(font)
        self.fu_button.setObjectName("fu_button")
        self.gridLayout.addWidget(self.fu_button, 5, 2, 1, 1)
        self.mu_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.mu_button.setFont(font)
        self.mu_button.setObjectName("mu_button")
        self.gridLayout.addWidget(self.mu_button, 6, 2, 1, 1)
        self.yu_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.yu_button.setFont(font)
        self.yu_button.setObjectName("yu_button")
        self.gridLayout.addWidget(self.yu_button, 7, 2, 1, 1)
        self.yo_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.yo_button.setFont(font)
        self.yo_button.setObjectName("yo_button")
        self.gridLayout.addWidget(self.yo_button, 7, 4, 1, 1)
        self.ke_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ke_button.setFont(font)
        self.ke_button.setObjectName("ke_button")
        self.gridLayout.addWidget(self.ke_button, 1, 3, 1, 1)
        self.se_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.se_button.setFont(font)
        self.se_button.setObjectName("se_button")
        self.gridLayout.addWidget(self.se_button, 2, 3, 1, 1)
        self.ko_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ko_button.setFont(font)
        self.ko_button.setObjectName("ko_button")
        self.gridLayout.addWidget(self.ko_button, 1, 4, 1, 1)
        self.so_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.so_button.setFont(font)
        self.so_button.setObjectName("so_button")
        self.gridLayout.addWidget(self.so_button, 2, 4, 1, 1)
        self.te_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.te_button.setFont(font)
        self.te_button.setObjectName("te_button")
        self.gridLayout.addWidget(self.te_button, 3, 3, 1, 1)
        self.to_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.to_button.setFont(font)
        self.to_button.setObjectName("to_button")
        self.gridLayout.addWidget(self.to_button, 3, 4, 1, 1)
        self.ne_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ne_button.setFont(font)
        self.ne_button.setObjectName("ne_button")
        self.gridLayout.addWidget(self.ne_button, 4, 3, 1, 1)
        self.wo_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.wo_button.setFont(font)
        self.wo_button.setObjectName("wo_button")
        self.gridLayout.addWidget(self.wo_button, 9, 4, 1, 1)
        self.wa_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.wa_button.setFont(font)
        self.wa_button.setObjectName("wa_button")
        self.gridLayout.addWidget(self.wa_button, 9, 0, 1, 1)
        self.ru_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ru_button.setFont(font)
        self.ru_button.setObjectName("ru_button")
        self.gridLayout.addWidget(self.ru_button, 8, 2, 1, 1)
        self.re_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.re_button.setFont(font)
        self.re_button.setObjectName("re_button")
        self.gridLayout.addWidget(self.re_button, 8, 3, 1, 1)
        self.ya_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ya_button.setFont(font)
        self.ya_button.setObjectName("ya_button")
        self.gridLayout.addWidget(self.ya_button, 7, 0, 1, 1)
        self.ra_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ra_button.setFont(font)
        self.ra_button.setObjectName("ra_button")
        self.gridLayout.addWidget(self.ra_button, 8, 0, 1, 1)
        self.me_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.me_button.setFont(font)
        self.me_button.setObjectName("me_button")
        self.gridLayout.addWidget(self.me_button, 6, 3, 1, 1)
        self.ro_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ro_button.setFont(font)
        self.ro_button.setObjectName("ro_button")
        self.gridLayout.addWidget(self.ro_button, 8, 4, 1, 1)
        self.ka_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ka_button.setFont(font)
        self.ka_button.setObjectName("ka_button")
        self.gridLayout.addWidget(self.ka_button, 1, 0, 1, 1)
        self.sa_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.sa_button.setFont(font)
        self.sa_button.setObjectName("sa_button")
        self.gridLayout.addWidget(self.sa_button, 2, 0, 1, 1)
        self.ta_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ta_button.setFont(font)
        self.ta_button.setObjectName("ta_button")
        self.gridLayout.addWidget(self.ta_button, 3, 0, 1, 1)
        self.na_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.na_button.setFont(font)
        self.na_button.setObjectName("na_button")
        self.gridLayout.addWidget(self.na_button, 4, 0, 1, 1)
        self.ha_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ha_button.setFont(font)
        self.ha_button.setObjectName("ha_button")
        self.gridLayout.addWidget(self.ha_button, 5, 0, 1, 1)
        self.ma_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ma_button.setFont(font)
        self.ma_button.setObjectName("ma_button")
        self.gridLayout.addWidget(self.ma_button, 6, 0, 1, 1)
        self.he_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.he_button.setFont(font)
        self.he_button.setObjectName("he_button")
        self.gridLayout.addWidget(self.he_button, 5, 3, 1, 1)
        self.no_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.no_button.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.no_button.setFont(font)
        self.no_button.setObjectName("no_button")
        self.gridLayout.addWidget(self.no_button, 4, 4, 1, 1)
        self.ho_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ho_button.setFont(font)
        self.ho_button.setObjectName("ho_button")
        self.gridLayout.addWidget(self.ho_button, 5, 4, 1, 1)
        self.mo_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.mo_button.setFont(font)
        self.mo_button.setObjectName("mo_button")
        self.gridLayout.addWidget(self.mo_button, 6, 4, 1, 1)
        self.n_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.n_button.setFont(font)
        self.n_button.setObjectName("n_button")
        self.gridLayout.addWidget(self.n_button, 10, 2, 1, 1)
        self.wi_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.wi_button.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.wi_button.setFont(font)
        self.wi_button.setObjectName("wi_button")
        self.gridLayout.addWidget(self.wi_button, 9, 1, 1, 1)
        self.we_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.we_button.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.we_button.setFont(font)
        self.we_button.setObjectName("we_button")
        self.gridLayout.addWidget(self.we_button, 9, 3, 1, 1)
        self.img_banner = QtWidgets.QLabel(Form)
        self.img_banner.setGeometry(QtCore.QRect(0, 0, 1024, 394))
        self.img_banner.setMinimumSize(QtCore.QSize(1024, 394))
        self.img_banner.setMaximumSize(QtCore.QSize(1024, 394))
        self.img_banner.setObjectName("img_banner")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Gojuuon - Learn Japanese Pronounciation"))
        self.a_button.setText(_translate("Form", "あ"))
        self.i_button.setText(_translate("Form", "い"))
        self.uButton.setText(_translate("Form", "う"))
        self.e_button.setText(_translate("Form", "え"))
        self.o_button.setText(_translate("Form", "お"))
        self.ki_button.setText(_translate("Form", "き"))
        self.shi_button.setText(_translate("Form", "し"))
        self.chi_button.setText(_translate("Form", "ち"))
        self.ni_button.setText(_translate("Form", "に"))
        self.hi_button.setText(_translate("Form", "ひ"))
        self.mi_button.setText(_translate("Form", "み"))
        self.ri_button.setText(_translate("Form", "り"))
        self.ku_button.setText(_translate("Form", "く"))
        self.su_button.setText(_translate("Form", "す"))
        self.tsu_button.setText(_translate("Form", "つ"))
        self.nu_button.setText(_translate("Form", "ぬ"))
        self.fu_button.setText(_translate("Form", "ふ"))
        self.mu_button.setText(_translate("Form", "む"))
        self.yu_button.setText(_translate("Form", "ゆ"))
        self.yo_button.setText(_translate("Form", "よ"))
        self.ke_button.setText(_translate("Form", "け"))
        self.se_button.setText(_translate("Form", "せ"))
        self.ko_button.setText(_translate("Form", "こ"))
        self.so_button.setText(_translate("Form", "そ"))
        self.te_button.setText(_translate("Form", "て"))
        self.to_button.setText(_translate("Form", "と"))
        self.ne_button.setText(_translate("Form", "ね"))
        self.wo_button.setText(_translate("Form", "を"))
        self.wa_button.setText(_translate("Form", "わ"))
        self.ru_button.setText(_translate("Form", "る"))
        self.re_button.setText(_translate("Form", "れ"))
        self.ya_button.setText(_translate("Form", "や"))
        self.ra_button.setText(_translate("Form", "ら"))
        self.me_button.setText(_translate("Form", "め"))
        self.ro_button.setText(_translate("Form", "ろ"))
        self.ka_button.setText(_translate("Form", "か"))
        self.sa_button.setText(_translate("Form", "さ"))
        self.ta_button.setText(_translate("Form", "た"))
        self.na_button.setText(_translate("Form", "な"))
        self.ha_button.setText(_translate("Form", "は"))
        self.ma_button.setText(_translate("Form", "ま"))
        self.he_button.setText(_translate("Form", "へ"))
        self.no_button.setText(_translate("Form", "の"))
        self.ho_button.setText(_translate("Form", "ほ"))
        self.mo_button.setText(_translate("Form", "も"))
        self.n_button.setText(_translate("Form", "ん"))
        self.wi_button.setText(_translate("Form", "ゐ"))
        self.we_button.setText(_translate("Form", "ゑ"))
        self.img_banner.setText(_translate("Form", "<html><head/><body><p><img src=\":/newPrefix/gojuuon-banner-new.jpg\"/></p></body></html>"))

#import 1_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

